# Generated by Django 5.2.10 on 2026-01-20 08:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Full screen hero image for the homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short bio or introduction text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_title',
            field=models.CharField(blank=True, help_text="Main heading for the introduction (e.g., 'National Art Master')", max_length=255),
        ),
    ]
