# Generated by Django 5.2.10 on 2026-01-20 08:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text='The detailed life story and artistic journey.')),
                ('honors', wagtail.fields.StreamField([('honor', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the award or honor', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year received', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Awarding organization', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('year', 1), ('organization', 2)]], {})}, help_text='List of honors and awards')),
                ('studio_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, help_text='Photos of the studio')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
